"""Trap-boundary generator: does the engine trap EXACTLY where the spec mandates — and NOT a step early/late?

A different oracle law from `compose` (value-preservation): here the per-program oracle is either a baked
`TRAP` or a baked constant, generated by sweeping each trappable operation across its boundary
`{edge-1, edge, edge+1}`. The prize is the off-by-one bounds check (`<=` vs `<`) on array / memory / table
accesses — a soundness escape if the engine reads one past the end — plus div/rem-by-zero and `INT_MIN/-1`,
`trunc` vs `trunc_sat` of out-of-range / NaN, a null-reference dereference, and a failing `ref.cast`. Half the
programs carry their own answer (a saturating conversion lands on a known constant); the other half expect a
mandated `TRAP`. No second engine required.
"""


def _array_oob(v):
    """array.get swept across the length-4 boundary: idx 3 is the last valid element, 4 is one past the end."""
    idx, exp = [(0, "OK 10"), (3, "OK 40"), (4, "TRAP"), (5, "TRAP")][v % 4]
    wat = ('(module (type $a (array i32))\n'
           '  (func (export "f") (result i32)\n'
           f'    (array.get $a (array.new_fixed $a 4 (i32.const 10) (i32.const 20) (i32.const 30) (i32.const 40)) (i32.const {idx}))))')
    return f"array-oob[{idx}]", exp, wat


def _memory_oob(v):
    """i32.load swept across the 1-page (65536-byte) boundary: 65532 is the last in-bounds 4-byte slot."""
    off, exp = [(0, "OK 12345"), (65532, "OK 0"), (65533, "TRAP"), (65536, "TRAP")][v % 4]
    wat = ('(module (memory 1)\n'
           '  (func (export "f") (result i32)\n'
           '    (i32.store (i32.const 0) (i32.const 12345))\n'
           f'    (i32.load (i32.const {off}))))')
    return f"memory-oob[{off}]", exp, wat


def _table_oob(v):
    """table.get swept across the size-2 boundary, read by ref.is_null (0 = in-bounds non-null, TRAP = OOB)."""
    idx, exp = [(0, "OK 0"), (1, "OK 0"), (2, "TRAP"), (3, "TRAP")][v % 4]
    wat = ('(module (table $t 2 funcref) (func $g) (elem (i32.const 0) $g $g)\n'
           '  (func (export "f") (result i32)\n'
           f'    (ref.is_null (table.get $t (i32.const {idx})))))')
    return f"table-oob[{idx}]", exp, wat


def _div(v):
    """integer division at its two trap points: a zero divisor and INT_MIN / -1 overflow."""
    num, den, exp = [(100, 7, "OK 14"), (100, 0, "TRAP"), (-2147483648, -1, "TRAP"), (-7, 2, "OK -3")][v % 4]
    wat = ('(module (func (export "f") (result i32)\n'
           f'    (i32.div_s (i32.const {num}) (i32.const {den}))))')
    return f"div[{num}/{den}]", exp, wat


def _trunc(v):
    """trunc (must trap out of range / on NaN) vs trunc_sat (must saturate to a known constant, never trap)."""
    op, val, exp = [("i32.trunc_f32_s", "3.7", "OK 3"), ("i32.trunc_f32_s", "1e10", "TRAP"),
                    ("i32.trunc_sat_f32_s", "1e10", "OK 2147483647"), ("i32.trunc_sat_f32_s", "nan", "OK 0"),
                    ("i32.trunc_f32_s", "nan", "TRAP")][v % 5]
    wat = ('(module (func (export "f") (result i32)\n'
           f'    ({op} (f32.const {val}))))')
    return f"trunc[{op.split('.')[1]},{val}]", exp, wat


def _null(v):
    """a struct.get / array.get on a null reference must trap; on a real reference it returns the field."""
    if v % 2 == 0:
        return "null-struct-get", "TRAP", ('(module (type $s (struct (field i32)))\n'
                                           '  (func (export "f") (result i32) (struct.get $s 0 (ref.null $s))))')
    return "nonnull-struct-get", "OK 99", ('(module (type $s (struct (field i32)))\n'
                                           '  (func (export "f") (result i32) (struct.get $s 0 (struct.new $s (i32.const 99)))))')


def _cast(v):
    """a ref.cast to an incompatible type must trap; to a compatible type it returns the cast reference."""
    if v % 2 == 0:
        return "refcast-fail", "TRAP", ('(module (type $s (struct (field i32)))\n'
                                        '  (func (export "f") (result i32)\n'
                                        '    (struct.get $s 0 (ref.cast (ref $s) (ref.i31 (i32.const 5))))))')
    return "refcast-ok", "OK 42", ('(module (type $s (struct (field i32)))\n'
                                   '  (func (export "f") (result i32)\n'
                                   '    (struct.get $s 0 (ref.cast (ref $s) (struct.new $s (i32.const 42))))))')


_FAMILIES = [_array_oob, _memory_oob, _table_oob, _div, _trunc, _null, _cast]


def trapline_gen(seed):
    """Return (label, export, expected, wat): the seed-th trap-boundary probe."""
    fam = _FAMILIES[seed % len(_FAMILIES)]
    label, expected, wat = fam(seed // len(_FAMILIES))
    return f"trapline-{label}", "f", expected, wat


if __name__ == "__main__":
    import subprocess, os
    os.environ["DYLD_LIBRARY_PATH"] = os.environ.get("WASMEDGE_LIB", os.path.expanduser("~/wasm-engines/wasmedge/lib"))
    ENG = os.path.expanduser("~/wasm-engines")
    REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    WT = f"{ENG}/wasmtime-v46/wasmtime"; WE = f"{ENG}/wasmedge/bin/wasmedge"
    MCR = f"{REPO}/runner/target/release/mc-runner"
    NODE = os.path.expanduser("~/.nvm/versions/node/v26.3.0/bin/node"); V8 = f"{REPO}/miscast/oracle/v8.js"

    import re

    def res(p):
        out = ((p.stdout or "") + (p.stderr or "")).lower()
        # a trap shows as a non-zero exit OR any engine's trap wording (wasmtime "trap", WasmEdge "execution
        # failed: integer overflow / out of bounds", V8 "RuntimeError", a cast failure, a null dereference).
        if p.returncode != 0 or any(k in out for k in (
                "trap", "unreachable", "out of bounds", "overflow", "invalid conversion", "cast",
                "execution failed", "null", "divide", "runtimeerror")):
            return "TRAP"
        m = re.findall(r"-?\d+", p.stdout or "")
        return f"OK {m[-1]}" if m else "OK _"

    def run(eng, wasm):
        if eng == "wt": c = [WT, "run", "-W", "function-references=y,gc=y", "--invoke", "f", wasm]
        elif eng == "we": c = [WE, "run", wasm, "f"]
        elif eng == "mcr": c = [MCR, wasm, "--invoke", "f"]
        elif eng == "v8": c = [NODE, V8, wasm, "f"]
        return res(subprocess.run(c, capture_output=True, text=True))

    print("=== trapline: conformant engines must trap exactly where the spec says (or hit the baked constant) ===")
    bad = 0
    for s in range(28):
        label, export, expected, wat = trapline_gen(s)
        open("/tmp/tl.wat", "w").write(wat)
        a = subprocess.run(["wasm-tools", "parse", "/tmp/tl.wat", "-o", "/tmp/tl.wasm"], capture_output=True, text=True)
        if a.returncode != 0:
            print(f"  ASMFAIL {label}: {a.stderr.strip().splitlines()[-1][:64]}"); bad += 1; continue
        row = {e: run(e, "/tmp/tl.wasm") for e in ("wt", "we", "mcr", "v8")}
        ok = all(v == expected for v in row.values())
        bad += not ok
        print(f"  {'OK ' if ok else 'FAIL'} {label:28} exp={expected:12} {row}")
    print(f"\n28 programs, {bad} disagreeing")
